### ISSUE TITLE
IE and FF support

### ISSUE THREAD

**Issue by miyconst** [StarcounterSamples/SysUpgrade#2] opened 2016-02-22 09:01 UTC
The new version with Polymer `1.2.4` does not work in IE and FF.

- FF - ignores model changes.
- IE - throws exception on page load.

Tested with:

1. Launcher.
2. Products.
3. SysUpgrade.

**Comment by warpech** [comment] 2016-02-22 09:10
Thanks for noticing. Looking into it now

**Comment by warpech** [comment] 2016-02-22 09:56
For me it is workable in FF and Edge after hard clearing of cache, with one problem: changes to model are observed after every second click.

I will fix this problem and ask you to re-test.

Btw. I think we need to revisit our caching rules, because the current ones are way too stubborn.

**Comment by miyconst** [comment] 2016-02-22 10:01
Are we targeting IE at all? I always test in IE 11, not only in Edge. If we don't care about it, then I won't spend time for it.

**Comment by warpech** [comment] 2016-02-22 10:09
PuppetJs works in any browser that support XmlHttpRequest. The problem is with Polymer and its bindings. Theoretically `puppet-client` should run in [every browser that Polymer supports](https://www.polymer-project.org/1.0/resources/compatibility.html). Practically, Polymer has tons of problems in IE so we cannot fix them but can learn to live with most of them. Let's try to support IE11 but not at a price of affecting our architecture. We are building for the future, not for the past.

**Comment by warpech** [comment] 2016-02-23 16:30
Seems that the problem is fully reproducible in the following conditions: 

- use browser FF, Edge or Safari
- use Launcher's `starcounter-include` (not the original `starcounter-include`)
- use Polymer 1.2 or 1.3

To fix the problem one must either:

1. disable `juicy-tile-table` in Launcher's `starcounter-include` (for example by 404'ing the HTML Import). Not really a solution :)
2. add the following line in `juicy-html`

```js
if (arrayOfElements[childNo]._pathEffector) {
    arrayOfElements[childNo]._pathEffector("model", arrayOfElements[childNo].model);
}
```

`_pathEffector` is an internal Polymer's implementation of `notifyPath`. I cannot just use `notifyPath`, becuse this call appears before `template[is=dom-bind]` has applied `Polymer.Base.mixin(model, this._modelApi);` (meaning that `notifyPath` is not ready to be called).

I will investigate more tomorrow. I don't want to add it the above code without understanding the reason.

**Comment by warpech** [comment] 2016-02-24 09:50
I didn't like the solution [2] from above, so I have investigated [1]. 

So why does j-t-l prevent binding from work? It is connected to the fact that j-t-l does not distribute `<template>` tags. 

Commenting out this line: [`!(child instanceof HTMLTemplateElement) &&`](https://github.com/Juicy/juicy-tile-list/blob/23ede2b50d0b93a852771b9dc81336fe70adb987/src/juicy-tile-list.html#L111) fixes this problem. But creates a new one - **templates get their own tiles**.

Easiest way to reproduce it without Starcounter:
1. Clone `git@github.com:StarcounterPrefabs/launcher-include.git`
2. `bower install`
3. Check how `launcher-include/demo/index.html` works in Chrome but does not work in any browser that uses the polyfill
4. Check how commenting out `!(child instanceof HTMLTemplateElement) &&` in `juicy-tile-list/src/juicy-tile-list.html` fixes the problem

@tomalec any suggestions how to proceed? I still don't know where to search for real solution to the problem: polyfill, Polymer or j-t-l?

**Comment by miyconst** [comment] 2016-02-24 09:53
@warpech could you please check whether adding:

```html
<content select="template"></content>
```

To https://github.com/Juicy/juicy-tile-list/blob/gh-pages/src/juicy-tile-list.html#L49 solves the problem?

**Comment by warpech** [comment] 2016-02-24 09:53
Or maybe I actually have a solution!!! It seems that adding this line: 

```html
<content></content>
``` 

after https://github.com/Juicy/juicy-tile-list/blob/23ede2b50d0b93a852771b9dc81336fe70adb987/src/juicy-tile-list.html#L49 fixes the problem without side effects. 

@tomalec any idea for explanation why is it not needed in Chrome but is needed in polyfill? Might it be an actual bug in Chrome?

**Comment by warpech** [comment] 2016-02-24 09:54
@miyconst great timing :) And I admire your skill of doing it without the research that I did. But why is it a problem at all? Any ideas?

**Comment by miyconst** [comment] 2016-02-24 09:59
@warpech I have spend some time investigating this issue for scripts and styles not being executed/applied in IE/FF.

It ended up that wc.js simply removes the nodes which are not distributed from Shadow DOM.

**Comment by tomalec** [comment] 2016-02-24 10:30
I think we can go with `<content select="template">` as interim state. 
However, the down sides are:
 - we can end up filtering any know node type, and it will me always one missing, like with j-t-l filtering elements
 - it would be harder to achieve with Shadow DOM v1

I would say that `<content>` (`<slot>`) could be a good solution, but then we will need to make sure hidden tiles are display none, instead of not-distributed (which should be current implementation, but I'm not 100% sure if it's guaranteed)

**Comment by tomalec** [comment] 2016-02-24 10:31
I think it's a bug in wc.js, possibly non-fixable. But could you chaeck with master branch of wc.js? there were some fixes regarding nested templates recently.

**Comment by warpech** [comment] 2016-02-24 10:31
> It ended up that wc.js simply removes the nodes which are not distributed in Shadow DOM.

...while Chrome keeps them, even though they are not distributed. I wonder what does the spec say. I can't find it: https://www.w3.org/TR/2014/WD-shadow-dom-20140617/

**Comment by warpech** [comment] 2016-02-24 10:32
> I think it's a bug in wc.js, possibly non-fixable. But could you chaeck with master branch of wc.js? there were some fixes regarding nested templates recently.

I am testing wcjs v0.7.21, which is the current head of the master branch

**Comment by tomalec** [comment] 2016-02-24 10:33
I think I have asked about it somewhere, but I cannot find where ;)

**Comment by tomalec** [comment] 2016-02-24 10:37
At https://www.w3.org/TR/html5/scripting-1.html#script I see no reason why `<script>` inserted into a Document should not be executed.

**Comment by warpech** [comment] 2016-02-24 10:38
Anyway, I think that the `content` solution is the way to go. Would you go with `<content select="template">` or `<content>`? I cannot think of a reason why it shouldn't be just `<content>`.

**Comment by tomalec** [comment] 2016-02-24 10:41
I would go with `<content>` unless you will find any bug with it. I think it was initially to serve hide feature, and to make sure only tiles are rendered, without inline texts etc.

**Comment by tomalec** [comment] 2016-02-24 11:02
I think this summarizes our concer about, how and why it should work http://w3c.github.io/webcomponents/spec/shadow/#html-elements-in-shadow-trees

> According to the [[HTML]](https://html.spec.whatwg.org/multipage/), some HTML Elements would have different behavior if they participate in a shadow tree, instead of a document tree, because their definitions require the elements to be in a document as a necessary condition for them to work. In other words, they shouldn't work if they participate in a shadow tree, even when they are in a composed document. We must fill this gap because we expect that most of HTML Elements behave in the same way as in a document, as long as they are in a composed document. See W3C [Bug 26365](https://github.com/w3c/webcomponents/issues/57) and [Bug 27406](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27406) for the details. The following is the tentative summary of the discussions in the W3C bugs. We, however, haven't covered all HTML Elements and their behaviors here yet. For HTML Elements which are not explicitly stated here, they should be considered as active in a shadow tree. We are trying to update [[HTML]](https://html.spec.whatwg.org/multipage/) itself, instead of having monkey patches here.

**Comment by warpech** [comment] 2016-02-24 12:34
Current Launcher (`master`) and SysUpgrade (`master`) are working in FF and Edge with the beforementioned `<content>` fix.

@miyconst could you please check again? Also, please check if this doesn't break any other known problems with `<script>` in IE and FF.

Btw. I have upgraded SysUpgrade to Polymer 1.3

**Comment by tomalec** [comment] 2016-02-24 12:48
https://github.com/Polymer/polymer/issues/3464

**Comment by miyconst** [comment] 2016-02-25 15:46
FF seems to work with the latest SysUpgrade, but IE still throws errors:

![image](https://cloud.githubusercontent.com/assets/6435556/13324744/4bff7862-dbdf-11e5-8ea8-5a308fb233dd.png)

The page is blank.

**Comment by warpech** [comment] 2016-02-25 16:00
Confirmed. 

Chrome, Firefox, Edge and Safari seem to work OK though

**Comment by warpech** [comment] 2016-02-25 16:14
Closed by accident

@miyconst believe it or not but the simple change from https://github.com/PuppetJs/puppet-polymer-client/commit/ad5f4e65cc1f0ad868c9b87904729e05582f5171 fixes IE11 somehow :)

**Comment by miyconst** [comment] 2016-02-25 16:17
That was an easy fix :)

**Comment by warpech** [comment] 2016-02-26 08:16
Closing this issue, because SysUpgrade generally works now in IE, FF and other polyfilled browsers. 

Specific problems (such as https://github.com/StarcounterSamples/Products/issues/8) are tracked in separate issues.

**Closed by warpech** 2016-02-26 08:16 UTC
Labels: bug
